# -*- after-save-hook: org-latex-export-to-pdf; -*-
#+latex_header: \usepackage[margin=2cm]{geometry}
#+latex_header: \usepackage{enumitem}
#+latex_header: \usepackage{multicol}
#+latex_header: \setlength{\parindent}{0cm}
#+latex_header: \usepackage{svg}
#+latex_header: \usepackage{caption}
#+latex_header: \captionsetup[table]{skip=5pt}
#+latex_header: \usepackage[brazil]{babel}
#+language: pt_BR

#+property: header-args+ :eval never-export

#+title: Aprendizado Descritivo
#+options: date:nil

* Definição
  Aprendizado descritivo se enquadra na seguinte classificação dos métodos de aprendizado
  de máquina:
  - Aprendizado preditivo: :: supervisionado ou não, tem como objetivo predizer dada
    característica (/target/).
  - Aprendizado descritivo: :: supervisionado ou não, tem como objetivo obter uma
    descrição para os dados.
  Contrastando, o aprendizado preditivo pretende prever dados futuros ou desconhecidos,
  enquando o apredizado descritivo prentende trazer uma instrospecção sobre os dados. Tal
  diferença pode se apresentar de forma tênue. Um exemplo são os algorítmos de
  agrupamento, que podem ser utilizados em ambas formas. Particularmente, o algorítmo
  /K-means/ se apresenta:
  - Preditivo: :: /K-means/: $P \to C$
  - Descritivo: :: /K-means/: $A \to C$
  Em aprendizado preditivo, o /K-means/ possui como domínio toda a população, ainda que o
  treinamento seja realizado apenas com uma amostra. Já no aprendizado descritivo, nos
  limitamos à amostra, afinal ela constitui o alvo total de análise.
* Mineração de itens frequentes
  Define-se como itens frequentes um conjunto itens que são recorrentes em um conjunto de
  transações. Considera-se nos conjuntos de dados:
  #+attr_latex: :options [itemsep=0pt]
  1. Os itens são os elementos do conjunto de variáveis de análise $I$.
  2. Um conjunto $X \subseteq I$ é denominado /itemset/.
  3. O conjunto de todos /k/-/itemsets/ é denotado port $I^{(k)}$.
  4. A amostra de transações é denominada por $T$.
  5. Cada transação é identificada unicamente por um =tid=.
  6. Um conjunto $Y \subseteq T$ é denominado /tidset/.
  7. Cada transação consiste de um identificador, e um conjunto de itens:
     $(\text{tid}, X),\> X \subseteq I$

  Formalmente, um conjunto de dados será uma tripla $(T, I, D)$, onde $D \subseteq T \times I$
  é uma relação binária:
  #+begin_export latex
  \[
    (t, i) \in D \iff \big[i \in X \text{ na transação } (t, X)\big]
  \]
  #+end_export
  @@latex:\newpage@@

  Uma transação pode *conter* um /itemset/, e tal relação é definida da seguinte forma:
  #+begin_export latex
  \[
    X \subseteq t \iff \forall\, i \in X: (t, i) \in D
  \]
  #+end_export
  O conjunto de transações que contém um /itemset/ $X$ é denominado *extensão* ou *cobertura* de $X$. \\
  Tal conjunto é definido pela seguinte operação:
  #+begin_export latex
  \begin{align*}
    & c: \mathcal{P}(I) \to \mathcal{P}(T) \\
    & c(X) = \big\{ t \in T \mid \forall\, i \in X: (t, i) \in D \big\}
  \end{align*}
  #+end_export
  Analogamente, o maior conjunto de itens comuns à um /tidset/ $Y$ é chamado de *intensão* de $Y$.
  #+begin_export latex
  \begin{align*}
    & i: \mathcal{P}(T) \to \mathcal{P}(I) \\
    & i(Y) = \big\{ x \in I \mid \forall\, t \in Y: (t, x) \in D \big\}
  \end{align*}
  #+end_export

  Desta forma, podemos representar um conjunto de dados de duas formas:
  - Horizontal: :: o conjunto de transações e suas intensões: $\big\{\big(t, i(\{t\})\big) \mid t \in T \big\}$
  - Vertical : :: o conjunto de itens e suas coberturas: $\big\{\big(x, c(\{x\})\big) \mid x \in I \big\}$
** Metodologia
   A identificação de regras de associação, em geral, envolve duas etapas:
   #+attr_latex: :options [itemsep=0pt]
   1. Mineração de conjuntos de itens frequentes
   2. Descoberta de regras de associação
   Devido à natureza computacionalmente intensa da primeira etapa, nossos estudos a focam. \\

   O limiar que separa os itens frequentes dos infrequentes é chamado de *suporte mínimo*. \\
   O suporte de um /itemset/ é o tamanho de sua cobertura:
   #+begin_export latex
   \[
     \text{sup}(X) = \big|c(X)\big|
   \]
   #+end_export
   Admite-se também a definição de *suporte relativo*:
   #+begin_export latex
   \[
     \text{rsup}(X) = \frac{\big|c(X)\big|}{|T|}
   \]
   #+end_export
** Algoritmos
   O espaço de busca do problema é o conjunto potência do conjunto de itens. Se
   considerarmos a relação de subconjuntos como uma relação de ordem parcial, temos que o
   espaço de busca é estruturado como um reticulado. Este reticulado pode ser visualizado
   como um grafo, onde somente as relações diretas são representadas.
   #+attr_latex: :options [label=$\to$]
   - Se $A \subseteq B \land |A| = |B| - 1$, então existe uma aresta de $A$ para $B$.
   Assim, a mineração de conjunto de itens frequentes é resolvida por uma busca neste
   reticulado, seja em largura ou em profundidade. De fato, existem abordagens baseadas em
   ambos métodos. \\

   No entanto, a maioria das abordagens compartilham a mesma estrutura de busca:
   #+attr_latex: :options [itemsep=0pt]
   1. Identificam candidatos navegando o espaço de busca
   2. Computam o suporte desses candidatos, descartando os infrequentes
   @@latex:\newpage@@
*** Algoritmo ingênuo
    Um algorítmo ingênuo é definido: enumerar cada /itemset/ possível, e verificar no
    conjunto de dados quais transações contêm esse /itemset/.
    #+attr_latex: :options [itemsep=0pt]
    - A computação do suporte de um /itemset/ requer uma passada sobre o conjunto de dados:
      $\mathcal{O}(|T|)$
    - Verificar se uma dada transação contém um /itemset/: $\mathcal{O}(|I|)$
    - Portanto, o custo total de computação do suporte é $\mathcal{O}(|I| \cdot |T|)$
    - O espaço de busca, por sua vez, é o conjunto potência de $I$.
    Logo, a complexidade do algoritmo ingênuo é $\mathcal{O}\big(2^{|I|} \cdot |I| \cdot |T|\big)$. \\

    Vale notar que, devido aos seus tamanhos, a memória principal tipicamente não comporta
    o conjunto de dados. Tal característica agrava fortemente a ineficiência deste
    algorítimo, onde o componente $\mathcal{O}(|I| \cdot |T|)$ corresponde à passadas no
    conjunto de dados.
*** Apriori
    O algoritmo Apriori é viabilizado pela propriedade de *anti-monotonicidade* da função
    suporte:
    #+begin_export latex
    \[
      A \subseteq B \implies \text{sup}(A) \geq \text{sup}(B)
    \]
    #+end_export
    O Apriori utiliza busca em largura para minerar os padrões. A busca inicia com a
    identificação dos itens frequentes. Depois, os conjuntos de tamanho $k$ são explorados
    antes dos imediatamente maiores. Assim como o ingênuo, ele também opera em duas etapas:
    #+attr_latex: :options [itemsep=0pt]
    1. Geração de candidatos
    2. Cálculo do suporte e eliminação dos infrequentes.
    Candidatos que diferem em apenas um item são combinados para gerar os próximos
    candidatos, de tamanho $k + 1$. Imediatamente, os que possuirem algum subconjunto
    infrequente são descartados. Utilizando este método, os suportes dos candidatos são
    atualizados com uma única passada no conjunto de dados. \\

    No total, o número de passadas é drasticamente reduzido: $\mathcal{O}(|I|)$ \\

    Apesar disso, o algoritmo ainda apresenta problemas:
    #+attr_latex: :options [itemsep=0pt]
    - Nem sempre a memória primária comporta todos candidatos de um nível, demandados para
      busca em largura.
    - As operações de poda e cálculo do suporte podem ser consideravelmente custosas, mas
      podem ser atenuadas com estruturas de dados apropriadas.
    - A redução do suporte mínimo implica um grande impacto no custo computacional, pois
      quanto mais profundo o nível, seu tamanho cresce exponencialmente.
    - A densidade da base de dados também decorre em um custo maior: transações com mais
      itens implicam /itemsets/ maiores, mais subconjuntos são gerados para a contagem do
      suporte.
    @@latex:\newpage@@
*** Equivalence Class Transformation
    O Eclat tem como proposta eliminar a necessidade de passadas no conjunto de dados para
    computar o suporte. Para isso, utiliza-se uma representação vertical dos dados, e o
    fato de que a cobertura da união de dois /itemsets/ é a interseção de suas coberturas. \\

    De forma equivalente, a ideia central do algoritmo é manter os /tidsets/ em memória
    principal para computar o suporte dos /itemsets/ através de interseções desses
    conjuntos. Contudo, a memória principal pode não comportar todos os /tidsets/. Assim, é
    necessário algum mecanismo que possibilite a divisão do espaço de busca em
    subproblemas independentes. \\

    Esta divisão pode ser feita conforme uma relação de equivalência estabelecida sobre os
    candidatos. Seja $p: \mathcal{P}(I) \times N \to \mathcal{P}(I)$ uma função prefixo. A
    seguinte relação é uma relação de equivalência:
    #+begin_export latex
    \begin{align*}
      & \theta_k \subseteq \mathcal{P}(I) \times \mathcal{P}(I) \\
      & A \> \theta_k \> B \equiv p(A, k) = p(B, k)
    \end{align*}
    #+end_export
    Dessa forma, induz-se uma partição dos conjuntos de itens em classes de equivalência,
    onde todos os elementos compartilham um certo prefixo. \\

    Durante a busca em profundidade, o algoritmo particiona os conjuntos de itens conforme
    a relação de equivalência e o nível da árvore. O cálculo do suporte no algoritmo se
    restringe a calcular o tamanho do /tidset/. \\

    Apesar disso, o algoritmo ainda apresenta problemas:
    #+attr_latex: :options [itemsep=0pt]
    - O tempo de execução depende do cálculo da interseção dos /tidsets/.
    - O custo computacional do algoritmo está diretamente relacionado ao tamanho dos
      /tidsets/.
    - O custo de espaço também depende do tamanho. Quanto mais denso o conjunto de dados,
      mais largos serão os /tidsets/.
*** dEclat
    De forma a atacar o problema de espaço do Eclat, podemos substituir os /tidsets/ pela
    diferença entre os mesmos e os prefixos que os definem para os membros de cada
    classe. Tal conjunto é denomidado *diffset*. Para um prefixo $P$ e um /itemset/ $PX$, o
    /diffset/ de $X$ é
    #+begin_export latex
    \[
      d(PX) = c(P) - c(X)
    \]
    #+end_export
    Somente os /diffsets/ são armazenados, portanto o suporte não é mais obtido como a
    cardinalidade desse conjunto. Calculamos o suporte de um /itemset/ $PXY$, obtido a
    partir de $PX$ e $PY$, da seguinte forma:
    #+begin_export latex
    \[
      \text{sup}(PXY) = \text{sup}(PX) - \left|d(PXY)\right|
    \]
    #+end_export
    Tal solução passa por computar o diffset de $PXY$:
    #+begin_export latex
    \[
      d(PXY) = d(PY) - d(PX)
    \]
    #+end_export
    Em outras palavras, podemos usar os diffsets dos conjuntos base para calcular o
    diffset do novo candidato. \\

    Essa abordagem se mostra muito eficiente para conjuntos densos. Porém, em conjuntos
    esparsos, o algoritmo original é a melhor opção.
*** FP-Growth
    O algoritmo FP-Growth procura atacar dois problemas presentes nas abordagens
    anteriores:
    #+attr_latex: :options [itemsep=0pt]
    - Repetidas passadas sobre a base de dados.
    - Geração de candidatos.
    Para isso:
    #+attr_latex: :options [itemsep=0pt]
    1. Adota-se uma estratégia de busca em profundidade.
    2. Adota-se projeções dos dados para mantê-los em memória principal.
    3. Utiliza-se uma árvore especial de prefixos denominada FP-Tree.
    4. Busca-se os padrões inteiramente através desta árvore, sem necessidade de retorno
       aos dados.
    A FP-Tree constitui uma árvore de prefixos tradicional, adicionada de uma tabela
    auxiliar de localização. Cada nó contém um item e sua frequência *naquele prefixo*.
    Portanto, um mesmo item pode constar em vários nós, caso ocorra em prefixos distintos.
    Já a tabela possui as seguintes colunas:
    #+attr_latex: :options [itemsep=0pt]
    - 1. Item: :: identificador do item, índice da tabela.
    - 2. Frequência: :: frequência individual de cada item (denota a ordem dos itens).
    - 3. Nós: :: coleção de referências para os nós da árvore referentes ao item.

    Sua construção se dá em duas fases:
    #+attr_latex: :options [itemsep=0pt]
    - 1. Computa-se a frequêcia individual dos itens: :: (Uma passada nos dados) \\
      Itens infrequentes são descartados, pois não podem formar padrões frequentes.
    - 2. Insere-se cada transação, através dos seus itens ordenados: :: (Outra passada) \\
      Itens são ordenados em ordem decrescente de frequência, sendo os infrequentes
      filtrados.

    Com a FP-Tree construída, inicia a mineração recursiva de padrões. \\

    Para cada item em ordem *crescente*:
    #+attr_latex: :options [itemsep=0pt]
    1. Constrói-se uma *nova FP-Tree* a partir dos prefixos deste item, desconsiderando o
       item em questão. É importante calcular as frequências apenas nos prefixos
       considerados.
    2. Desta, descarta-se os itens cuja frequência na árvore é inferior ao suporte
       mínimo. 
    3. Caso a árvore constitua um ramo, considera-se este ramo um conjunto, e deste
       extrai-se o conjunto potência. Caso contrário, repete-se o processo recursivamente
       para cada item da árvore.
    4. Finalmente, acresce-se aos conjuntos extraídos o item da iteração.

    *Exemplo*: (suporte mínimo = 2)
    #+caption: Base de dados
    | /tid/ | a            | b            | c            | d            | e            | f            |
    |-----+--------------+--------------+--------------+--------------+--------------+--------------|
    |   1 | $\checkmark$ |              | $\checkmark$ | $\checkmark$ |              | $\checkmark$ |
    |   2 |              | $\checkmark$ | $\checkmark$ |              |              |              |
    |   3 |              |              | $\checkmark$ |              | $\checkmark$ | $\checkmark$ |
    |   4 | $\checkmark$ |              |              | $\checkmark$ |              |              |
    |   5 |              | $\checkmark$ | $\checkmark$ |              |              | $\checkmark$ |
    |   6 | $\checkmark$ |              | $\checkmark$ |              |              | $\checkmark$ |

    #+latex: \newpage

    Construção da FP-Tree:
    #+latex: \begin{multicols}{2}
    1. Cálculo da frequência:
       #+begin_src dot :file images/fp-tree-1.svg
         graph g {
           graph [ bgcolor = transparent ]
           node [ shape=circle ]
           Ø;
           tbl [
             shape = plaintext
             label = <
               <table border='0' cellspacing='0'>
                 <tr><td>Item</td><td>Frequência</td><td>Nós</td></tr>
                 <tr><td>c</td><td>5</td><td>Ø</td></tr>
                 <tr><td>f</td><td>4</td><td>Ø</td></tr>
                 <tr><td>a</td><td>3</td><td>Ø</td></tr>
                 <tr><td>b</td><td>2</td><td>Ø</td></tr>
                 <tr><td>d</td><td>2</td><td>Ø</td></tr>
               </table>
             >
           ]
         }
       #+end_src
       #+attr_latex: :width 150px
       #+results:
       [[file:images/fp-tree-1.svg]]
       #+latex: \vfill\null\columnbreak
    2. Inserção das transações:
       #+begin_src dot :file images/fp-tree-2.svg
         graph g {
           graph [ bgcolor = transparent ]
           node [ shape=circle, margin = 0 ]
   
           root [ label = Ø ];
           c1 [ label = "c(5)", color = violet ]
           f1 [ label = "f(4)", color = orange ]
           a1 [ label = "a(2)", color = lightgreen ]
           d1 [ label = "d(1)", color = dodgerblue ]
           b1 [ label = "b(1)", color = crimson ]
           b2 [ label = "b(1)", color = crimson ]
           a2 [ label = "a(1)", color = lightgreen ]
           d2 [ label = "d(1)", color = dodgerblue ]
   
           tbl [
             shape = plaintext
             label = <
               <table border='0' cellspacing='0'>
                 <tr><td>Item</td><td>Frequência</td><td>Nós</td></tr>
                 <tr><td>c</td><td>5</td><td bgcolor='violet'>1</td></tr>
                 <tr><td>f</td><td>4</td><td bgcolor='orange'>1</td></tr>
                 <tr><td>a</td><td>3</td><td bgcolor='lightgreen'>2</td></tr>
                 <tr><td>b</td><td>2</td><td bgcolor='crimson'>2</td></tr>
                 <tr><td>d</td><td>2</td><td bgcolor='dodgerblue'>2</td></tr>
               </table>
             >
           ]
   
           root -- c1
           c1 -- f1
           f1 -- a1
           a1 -- d1
           f1 -- b1
           c1 -- b2
           root -- a2
           a2 -- d2
         }
       #+end_src
       #+attr_latex: :width 230px
       #+results:
       [[file:images/fp-tree-2.svg]]
    #+latex: \end{multicols}

    Mineração de padrões a partir do item $d$:
    #+latex: \begin{multicols}{2}
    #+attr_latex: :options [itemsep=0pt]
    1. Projeção dos prefixos:
       #+begin_src dot :file images/fp-tree-3.svg
         graph g {
           graph [ bgcolor = transparent ]
           node [ shape=circle, margin = 0 ]

           root [ label = Ø ];
           c1 [ label = "c(1)", color = violet ]
           f1 [ label = "f(1)", color = orange ]
           a1 [ label = "a(1)", color = lightgreen ]
           a2 [ label = "a(1)", color = lightgreen ]

           tbl [
             shape = plaintext
             label = <
               <table border='0' cellspacing='0'>
                 <tr><td>Item</td><td>Frequência</td><td>Nós</td></tr>
                 <tr><td>a</td><td>2</td><td bgcolor='lightgreen'>2</td></tr>
                 <tr><td>c</td><td>1</td><td bgcolor='violet'>1</td></tr>
                 <tr><td>f</td><td>1</td><td bgcolor='orange'>1</td></tr>
               </table>
             >
           ]

           root -- c1
           c1 -- f1
           f1 -- a1
           root -- a2
         }
       #+end_src
       #+attr_latex: :width 170px
       #+results:
       [[file:images/fp-tree-3.svg]]
    2. Remoção dos infrequentes:
       #+begin_src dot :file images/fp-tree-4.svg
         graph g {
           graph [ bgcolor = transparent ]
           node [ shape=circle, margin = 0 ]

           root [ label = Ø ];
           a1 [ label = "a(2)", color = lightgreen ]

           tbl [
             shape = plaintext
             label = <
               <table border='0' cellspacing='0'>
                 <tr><td>Item</td><td>Frequência</td><td>Nós</td></tr>
                 <tr><td>a</td><td>2</td><td bgcolor='lightgreen'>1</td></tr>
               </table>
             >
           ]

           root -- a1
         }
       #+end_src
       #+attr_latex: :width 140px
       #+results:
       [[file:images/fp-tree-4.svg]]
       Padrões extraídos: $\{d\}, \{a,d\}$
    #+latex: \end{multicols}

    #+latex: \newpage

    Mineração de padrões a partir do item $b$:
    #+latex: \begin{multicols}{2}
    #+attr_latex: :options [itemsep=0pt]
    1. Projeção dos prefixos:
       #+begin_src dot :file images/fp-tree-5.svg
         graph g {
           graph [ bgcolor = transparent ]
           node [ shape=circle, margin = 0 ]

           root [ label = Ø ];
           c1 [ label = "c(2)", color = violet ]
           f1 [ label = "f(1)", color = orange ]

           tbl [
             shape = plaintext
             label = <
               <table border='0' cellspacing='0'>
                 <tr><td>Item</td><td>Frequência</td><td>Nós</td></tr>
                 <tr><td>c</td><td>2</td><td bgcolor='violet'>1</td></tr>
                 <tr><td>f</td><td>1</td><td bgcolor='orange'>1</td></tr>
               </table>
             >
           ]

           root -- c1
           c1 -- f1
         }
       #+end_src
       #+attr_latex: :width 140px
       #+results:
       [[file:images/fp-tree-5.svg]]
    2. Remoção dos infrequentes:
       #+begin_src dot :file images/fp-tree-6.svg
         graph g {
           graph [ bgcolor = transparent ]
           node [ shape=circle, margin = 0 ]

           root [ label = Ø ];
           c1 [ label = "c(2)", color = violet ]

           tbl [
             shape = plaintext
             label = <
               <table border='0' cellspacing='0'>
                 <tr><td>Item</td><td>Frequência</td><td>Nós</td></tr>
                 <tr><td>c</td><td>2</td><td bgcolor='violet'>1</td></tr>
               </table>
             >
           ]

           root -- c1
         }
       #+end_src
       #+attr_latex: :width 140px
       #+results:
       [[file:images/fp-tree-6.svg]]
       Padrões extraídos: $\{b\}, \{c,b\}$
    #+latex: \end{multicols}

    Mineração de padrões a partir do item $a$:
    #+latex: \begin{multicols}{2}
    #+attr_latex: :options [itemsep=0pt]
    1. Projeção dos prefixos:
       #+begin_src dot :file images/fp-tree-7.svg
         graph g {
           graph [ bgcolor = transparent ]
           node [ shape=circle, margin = 0 ]

           root [ label = Ø ];
           c1 [ label = "c(2)", color = violet ]
           f1 [ label = "f(2)", color = orange ]

           tbl [
             shape = plaintext
             label = <
               <table border='0' cellspacing='0'>
                 <tr><td>Item</td><td>Frequência</td><td>Nós</td></tr>
                 <tr><td>c</td><td>2</td><td bgcolor='violet'>1</td></tr>
                 <tr><td>f</td><td>2</td><td bgcolor='orange'>1</td></tr>
               </table>
             >
           ]

           root -- c1
           c1 -- f1
         }
       #+end_src
       #+attr_latex: :width 140px
       #+results:
       [[file:images/fp-tree-7.svg]]
    2. Não há infrequentes.

       Padrões extraídos: $\{a\}, \{c,a\}, \{a,f\}, \{c,f,a\}$
    #+latex: \end{multicols}

    Mineração de padrões a partir do item $f$:
    #+latex: \begin{multicols}{2}
    #+attr_latex: :options [itemsep=0pt]
    1. Projeção dos prefixos:
       #+begin_src dot :file images/fp-tree-8.svg
         graph g {
           graph [ bgcolor = transparent ]
           node [ shape=circle, margin = 0 ]

           root [ label = Ø ];
           c1 [ label = "c(4)", color = violet ]

           tbl [
             shape = plaintext
             label = <
               <table border='0' cellspacing='0'>
                 <tr><td>Item</td><td>Frequência</td><td>Nós</td></tr>
                 <tr><td>c</td><td>4</td><td bgcolor='violet'>1</td></tr>
               </table>
             >
           ]

           root -- c1
         }
       #+end_src
       #+attr_latex: :width 140px
       #+results:
       [[file:images/fp-tree-8.svg]]
    2. Não há infrequentes.

       Padrões extraídos: $\{f\}, \{c,f\}$
    #+latex: \end{multicols}

    Mineração de padrões a partir do item $f$:
    #+latex: \begin{multicols}{2}
    #+attr_latex: :options [itemsep=0pt]
    1. Projeção dos prefixos:
       #+begin_src dot :file images/fp-tree-9.svg
         graph g {
           graph [ bgcolor = transparent ]
           node [ shape=circle, margin = 0 ]

           root [ label = Ø ];

           tbl [
             shape = plaintext
             label = <
               <table border='0' cellspacing='0'>
                 <tr><td>Item</td><td>Frequência</td><td>Nós</td></tr>
                 <tr><td>-</td><td>-</td><td>-</td></tr>
               </table>
             >
           ]
         }
       #+end_src
       #+attr_latex: :width 140px
       #+results:
       [[file:images/fp-tree-9.svg]]
    2. Não há infrequentes.

       Padrões extraídos: $\{c\}$
    #+latex: \end{multicols}

** Representações compactas
   Considerande uma base de dados contendo apenas duas transações:
   #+begin_export latex
   \begin{align*}
     \{ & \\
     & (0, a_{1}, \hdots, a_{50}), \\
     & (1, a_{1}, \hdots, a_{100}) \\
     \} &
   \end{align*}
   #+end_export
   Ao considerar um suporte mínimo igual a 2, essa base apresenta uma quantidade
   exorbitante de /itemsets/ frequentes:
   #+begin_export latex
   \[
     {100 \choose 1} + \hdots + {100 \choose 100} = 2^{100} - 1
   \]
   #+end_export
   Apesar de ser um caso extremo, é comum encontrar pequenas ocorrências deste padrão em
   bases de dados maiores. Isso inviabiliza a computação utilizando os métodos descritos
   anteriormente. \\

   De forma a mitigar este problema, utilizamos representações compactas dos /itemsets/
   frequentes.
*** Fronteira da frequência
    Uma forma de representação compacta denominada /Itemsets/ máximos é obtida ao se
    considerar o limiar entre os /itemsets/ frequentes e infrequentes. Os /Itemsets/ máximos
    são os /itemsets/ frequentes que não possuem superconjuntos frequentes.

    #+begin_src dot :file images/maximal-itemsets.svg
      graph G {
        graph [bgcolor = transparent, rankdir = "TD"]

        subgraph lvl0 {
          rank = same
          ∅ [label = "Ø\n1,2,3,4,5,6", fillcolor = ivory, style = filled]
        }
        subgraph lvl1 {
          rank = same
          "{a}" [label = "{a}\n1,4,6", fillcolor = ivory, style = filled]
          "{b}" [label = "{b}\n2,5", fillcolor = ivory, style = filled]
          "{c}" [label = "{c}\n1,2,3,5,6", fillcolor = ivory, style = filled]
          "{d}" [label = "{d}\n1,4", fillcolor = ivory, style = filled]
        }
        subgraph lvl2 {
          rank = same
          "{a,b}" [label = "{a,b}\nØ"]
          "{a,c}" [label = "{a,c}\n1,6", fillcolor = ivory, style = filled]
          "{a,d}" [label = "{a,d}\n1,4", fillcolor = ivory, style = filled]
          "{b,c}" [label = "{b,c}\n2,5", color = crimson, fillcolor = ivory, style = filled]
          "{b,d}" [label = "{b,d}\nØ"]
          "{c,d}" [label = "{c,d}\nØ"]
        }
        subgraph lvl3 {
          rank = same
          "{a,b,c}" [label = "{a,b,c}\nØ"]
          "{a,b,d}" [label = "{a,b,d}\nØ"]
          "{a,c,d}" [label = "{a,c,d}\n1", color = crimson, fillcolor = ivory, style = filled]
          "{b,c,d}" [label = "{b,c,d}\nØ"]
        }
        subgraph lvl4 {
          rank = same
          "{a,b,c,d}" [label = "{a,b,c,d}\nØ"]
        }
        subgraph lvl5 {
          rank = same
        }

        ∅ -- "{a}"
        ∅ -- "{b}"
        ∅ -- "{c}"
        ∅ -- "{d}"

        "{a}" -- "{a,b}"
        "{a}" -- "{a,c}"
        "{a}" -- "{a,d}"
        "{b}" -- "{a,b}"
        "{b}" -- "{b,c}"
        "{b}" -- "{b,d}"
        "{c}" -- "{a,c}"
        "{c}" -- "{b,c}"
        "{c}" -- "{c,d}"
        "{d}" -- "{a,d}"
        "{d}" -- "{b,d}"
        "{d}" -- "{c,d}"

        "{a,b}" -- "{a,b,c}"
        "{a,b}" -- "{a,b,d}"
        "{a,c}" -- "{a,b,c}"
        "{a,c}" -- "{a,c,d}"
        "{a,d}" -- "{a,b,d}"
        "{a,d}" -- "{a,c,d}"
        "{b,c}" -- "{a,b,c}"
        "{b,c}" -- "{b,c,d}"
        "{b,d}" -- "{a,b,d}"
        "{b,d}" -- "{b,c,d}"
        "{c,d}" -- "{a,c,d}"
        "{c,d}" -- "{b,c,d}"

        "{a,b,c}" -- "{a,b,c,d}"
        "{a,b,d}" -- "{a,b,c,d}"
        "{a,c,d}" -- "{a,b,c,d}"
        "{b,c,d}" -- "{a,b,c,d}"
      }
    #+end_src
    #+attr_latex: :width 350px
    #+results:
    [[file:images/maximal-itemsets.svg]]

    Apesar de ser uma represetação bastante compacta, o cálculo do suporte para os
    /itemsets/ derivados dessa representação não é viável de forma direta, sendo necessária
    uma nova passada na base de dados.

    #+latex: \newpage
*** Classes de equivalência
    Uma outra forma de obter representações compactas é particionar os /itemsets/ em classes
    de equivalência, definidas pela cobertura. 

    #+begin_src dot :file images/equivalence-classes.svg
      graph G {
        graph [bgcolor = transparent, rankdir = "TD"]

        subgraph lvl0 {
          rank = same
          ∅ [label = "Ø\n1,2,3,4,5,6", color = gray]
        }
        subgraph lvl1 {
          rank = same
          "{a}" [label = "{a}\n1,4,6", color = green]
          "{b}" [label = "{b}\n2,5", color = crimson]
          "{c}" [label = "{c}\n1,2,3,5,6", color = cyan]
          "{d}" [label = "{d}\n1,4", color = purple]
        }
        subgraph lvl2 {
          rank = same
          "{a,b}" [label = "{a,b}\nØ"]
          "{a,c}" [label = "{a,c}\n1,6", color = blue]
          "{a,d}" [label = "{a,d}\n1,4", color = purple]
          "{b,c}" [label = "{b,c}\n2,5", color = crimson]
          "{b,d}" [label = "{b,d}\nØ"]
          "{c,d}" [label = "{c,d}\n1", color = orange]
        }
        subgraph lvl3 {
          rank = same
          "{a,b,c}" [label = "{a,b,c}\nØ"]
          "{a,b,d}" [label = "{a,b,d}\nØ"]
          "{a,c,d}" [label = "{a,c,d}\n1", color = orange]
          "{b,c,d}" [label = "{b,c,d}\nØ"]
        }
        subgraph lvl4 {
          rank = same
          "{a,b,c,d}" [label = "{a,b,c,d}\nØ"]
        }
        subgraph lvl5 {
          rank = same
        }

        ∅ -- "{a}"
        ∅ -- "{b}"
        ∅ -- "{c}"
        ∅ -- "{d}"

        "{a}" -- "{a,b}"
        "{a}" -- "{a,c}"
        "{a}" -- "{a,d}"
        "{b}" -- "{a,b}"
        "{b}" -- "{b,c}"
        "{b}" -- "{b,d}"
        "{c}" -- "{a,c}"
        "{c}" -- "{b,c}"
        "{c}" -- "{c,d}"
        "{d}" -- "{a,d}"
        "{d}" -- "{b,d}"
        "{d}" -- "{c,d}"

        "{a,b}" -- "{a,b,c}"
        "{a,b}" -- "{a,b,d}"
        "{a,c}" -- "{a,b,c}"
        "{a,c}" -- "{a,c,d}"
        "{a,d}" -- "{a,b,d}"
        "{a,d}" -- "{a,c,d}"
        "{b,c}" -- "{a,b,c}"
        "{b,c}" -- "{b,c,d}"
        "{b,d}" -- "{a,b,d}"
        "{b,d}" -- "{b,c,d}"
        "{c,d}" -- "{a,c,d}"
        "{c,d}" -- "{b,c,d}"

        "{a,b,c}" -- "{a,b,c,d}"
        "{a,b,d}" -- "{a,b,c,d}"
        "{a,c,d}" -- "{a,b,c,d}"
        "{b,c,d}" -- "{a,b,c,d}"
      }
    #+end_src
    #+attr_latex: :width 350px
    #+results:
    [[file:images/equivalence-classes.svg]]

    Tal consideração permite duas formas de representações compactas:
   - /Itemsets/ fechados: :: são os *maiores* /itemsets/ das classes de equivalência. \\
     No exemplo:
     #+latex: \begin{multicols}{2}
     #+attr_latex: :options [itemsep=0pt]
     - $\{a\}$
     - $\{c\}$
     - $\{a,d\}$
     #+attr_latex: :options [itemsep=0pt]
     - $\{b,c\}$
     - $\{a,c\}$
     - $\{a,c,d\}$
     #+latex: \end{multicols}
   - /Itemsets/ geradores mínimos: :: são os *menores* /itemsets/ das classes de equivalência. \\
     No exemplo:
     #+latex: \begin{multicols}{2}
     #+attr_latex: :options [itemsep=0pt]
     - $\{a\}$
     - $\{b\}$
     - $\{c\}$
     #+attr_latex: :options [itemsep=0pt]
     - $\{d\}$
     - $\{a,c\}$
     - $\{c,d\}$
     #+latex: \end{multicols}
   
   Enquanto os /itemsets/ fechados são únicos, os geradores mínimos não necessariamente
   são. Portanto, a representação utilizando geradores mínimos pode apresentar
   redundância, não sendo muito compacta em casos extremos.

   #+latex:\newpage
*** Algoritmos
    Apesar de ser possível embutir tais representações nos algoritmos descritos
    anteriormente, isso apenas auxiliaria na digestão dos resultados, não apresentado
    ganho de desempenho computacional algum. De forma a explorar tal possibilidade de
    ganho computacional, algoritmos específicos se fazem necessários.
    - MAFIA: :: /Maximal Frequent Itemset Algorithm/ \\
      O algoritmo utiliza uma abordagem /best-first/branch-and-bound/ para navegar o
      reticulado, adotando uma representação vertical dos dados. Além disso, explora a
      ordem lexicográfica dos itens, bem como a relação de ordem parcial de subconjuntos
      entre os /itemsets/.

      Duas podas são realizadas:
      - Reordenamento dinâmico: Ao visitar cada nó na busca em profundidade, seus filhos
        imediatos são verificados, e os itens que causam infrequência são desconsiderados
        para a subárvore atual.
      - /Parent Equivalence Pruning/ (PEP): Caso a cobertura de um dos itens candidatos seja
        superior à do /itemset/ atual, ele é imediatamente adicionado a este /itemset/,
        restringindo buscas adicionais relativas à este item.
    - DCI Closed: :: @@latex:\hfill@@ \\
      O algoritmo utiliza uma abordagem de divisão e conquista no reticulado, adotano uma
      representação vertical dos dados. Tal abordagem se mostra extremamente interessante
      na medida que permite a paralelização da execução do algoritmo. Além disso, também
      explora uma ordem lexicográfica sobre os itens, e sua extensão sobre os /itemsets/.

      A ideia central do algoritmo é escalar o reticulado, visitando cada classe de
      equivalência uma única vez. Somente um candidato de cada classe é avaliado, e novos
      candidatos são gerados estendendo os conjuntos fechados com itens ainda não
      investigados.
